"""added

Revision ID: ce12c32cb500
Revises: 5d0e9399d155
Create Date: 2025-06-15 02:27:41.551239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce12c32cb500'
down_revision: Union[str, None] = '5d0e9399d155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_tracks', sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_tracks', 'added_at')
    # ### end Alembic commands ###
